### ISSUE TITLE
Issue - Error 503 - Service Temporarily Unavailable

### ISSUE THREAD

**Issue by jcsimko** [ca-cwds/Sandbox#2]
## Issue Description

Periodically receive "Error 503 - Service Temporarily Unavailable" page when saving data.

## Business Impact

Impacts ability to do user testing.

## Date/Time of first occurrence

First reported on 2017-04-27

## Is the Issue Repeatable?

Unsure

**Comment by jcsimko** [comment]
@ca-cwds/devops-eng - Please look into this.

**Comment by chadbratton** [comment]
Bug Story has been created within the DevOps backlog: https://www.pivotaltracker.com/story/show/144725199

**Comment by david-sanabria** [comment]
As of Thursday afternoon (27-Apr-2017), service was restored. This issue was initially reported in the DevOps issue log (https://github.com/ca-cwds/devops/issues/10) by Monte Williams. We had to disable some of the redundant components (used for high availability) in the Sandbox to stabilize the environment, but do not have a root cause. Root cause is still being investigated.
